spring.application.name=app
//spring.profiles.active=development
spring.profiles.active=production
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/store
spring.datasource.username=root
spring.datasource.password=singing1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port = 3000
//spring.jpa.show-sql=false
# This file is safe to push to GitHub because it contains no real passwords
# standard Spring Boot configuration

spring.jpa.open-in-view=false
server.forward-headers-strategy=FRAMEWORK

# 1. Force Hibernate to print every generated SQL query to the console
spring.jpa.show-sql=false
//spring.jpa.properties.hibernate.format_sql=false


spring.servlet.multipart.enabled=true

# Inside your local / dev configuration profile ONLY
rsa.private-key=classpath:certs/private.pem
rsa.public-key=classpath:certs/public.pem


# Tell Spring Security where your public key is located
#spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:certs/public.pem

# The maximum size allowed for a single uploaded file
spring.servlet.multipart.max-file-size=5MB

# The maximum size allowed for the whole request (file + text data)
spring.servlet.multipart.max-request-size=5MB
# Default session timeout (in seconds)
#server.servlet.session.timeout=600

# Enable JDBC session (if using JDBC)
#spring.session.store-type=jdbc

# Enable Redis session (if using Redis)
# spring.session.store-type=redis
app.admin.username=${APP_ADMIN_USERNAME}
app.admin.password=${APP_ADMIN_PASSWORD}


# The flat rate displayed anonymously to the buyer
shipping.buyer-contribution-single= 9.99
shipping.buyer-contribution-group= 12.99

stripe.api-key=${STRIPE_API_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}

stripe.success-url: ${FRONTEND_URL}/checkout/success?session_id={CHECKOUT_SESSION_ID}
stripe.cancel-url: ${FRONTEND_URL}/checkout/cancel
app.domain=${APP_DOMAIN}

# ==========================================================================
# ? CORRECTED GMAIL SMTP SERVER CONFIGURATIONS
# ==========================================================================
# 1. FIXED: Removed the accidental url protocol prefix text strings
spring.mail.host=smtp.gmail.com

# 2. FIXED: Corrected the standard secure TLS port assignment number
spring.mail.port=587

spring.mail.username=admin.kasoa.pl@gmail.com
spring.mail.password=ecijyqghxokkaiiv


# Essential connection and handshake encryption mappings
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

